// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MindSculpt",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "MindSculpt",
            targets: ["AppModule"],
            bundleIdentifier: "com.olmos.MindSculpt",
            teamIdentifier: "VQ8XWX6F86",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            // ✅ FIX: Declaración canónica de permisos para proyectos .swiftpm.
            // El Info.plist no es siempre respetado en Swift Playgrounds App;
            // este array es el origen autoritativo de capabilities y purpose strings.
            // Sin esto, AVCaptureDevice.authorizationStatus / requestAccess
            // disparan __abort_with_payload y el sistema mata la app.
            capabilities: [
                .camera(purposeString: "MindSculpt necesita acceso a la cámara para capturar colores calmantes que te ayuden a reducir tu estrés."),
                .motion(purposeString: "Detectamos el movimiento del dispositivo para que sacudirlo te ayude a liberar tensión emocional.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)

